import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "kn" | "hi";

const translations: Record<string, Record<Language, string>> = {
  // App identity
  appName:            { en: "Mitra",                      kn: "ಮಿತ್ರ",                       hi: "मित्र" },
  tagline:            { en: "Marine Safety Platform",      kn: "ಸಮುದ್ರ ಸುರಕ್ಷಾ ವೇದಿಕೆ",       hi: "समुद्री सुरक्षा मंच" },
  letsStart:          { en: "Let's Start",                 kn: "ಪ್ರಾರಂಭಿಸೋಣ",                  hi: "शुरू करें" },

  // Bottom Nav
  home:               { en: "Home",                        kn: "ಮುಖಪುಟ",                       hi: "होम" },
  map:                { en: "Map",                         kn: "ನಕ್ಷೆ",                         hi: "नक्शा" },
  alerts:             { en: "Alerts",                      kn: "ಎಚ್ಚರಿಕೆಗಳು",                  hi: "अलर्ट" },
  profile:            { en: "Profile",                     kn: "ಪ್ರೊಫೈಲ್",                     hi: "प्रोफ़ाइल" },

  // Dashboard menu
  chatbot:            { en: "Ask Mitra",                   kn: "ಮಿತ್ರನಿಗೆ ಕೇಳಿ",                  hi: "मित्र से पूछें" },
  sosEmergency:       { en: "SOS Emergency",               kn: "SOS ತುರ್ತು",                   hi: "SOS आपातकाल" },
  pfzFinderTitle:     { en: "PFZ Finder",                  kn: "ಮೀನುಗಾರಿಕೆ ವಲಯ ಪತ್ತೆ",           hi: "PFZ खोजक" },
  weather:            { en: "Weather",                     kn: "ಹವಾಮಾನ",                       hi: "मौसम" },
  fishMarket:         { en: "Fish Market",                 kn: "ಮೀನು ಮಾರುಕಟ್ಟೆ",             hi: "मछली बाजार" },
  safety:             { en: "Safety Drills",               kn: "ಸುರಕ್ಷಾ ತರಬೇತಿ",              hi: "सुरक्षा अभ्यास" },
  seaMap:             { en: "Sea Map",                     kn: "ಸಮುದ್ರ ನಕ್ಷೆ",                hi: "समुद्र नक्शा" },
  seaExplorer:        { en: "Sea Explorer",                kn: "ಸಮುದ್ರ ಅನ್ವೇಷಕ",                 hi: "समुद्र अन्वेषक" },
  realTimeNav:        { en: "Real-time maritime navigation", kn: "ನೈಜ ಸಮಯದ ಸಮುದ್ರ ನ್ಯಾವಿಗೇಷನ್",   hi: "वास्तविक समय समुद्री नेविगेशन" },
  rescueModeActive:   { en: "Rescue Mode Active",          kn: "ರಕ್ಷಣಾ ಮೋಡ್ ಸಕ್ರಿಯ",            hi: "बचाव मोड सक्रिय" },
  vesselPosition:     { en: "Vessel Position",             kn: "ನೌಕೆಯ ಸ್ಥಾನ",                   hi: "जहाज की स्थिति" },
  safeCorridor:       { en: "Safe Corridor",               kn: "ಸುರಕ್ಷಿತ ಹಾದಿ",                  hi: "सुरक्षित गलियारा" },
  stableSea:          { en: "Stable Sea",                  kn: "ಸ್ಥಿರ ಸಮುದ್ರ",                   hi: "स्थिर समुद्र" },
  dangerZone:         { en: "Danger Zone",                 kn: "ಅಪಾಯಕಾರಿ ವಲಯ",                 hi: "खतरा क्षेत्र" },
  rescueTarget:       { en: "Rescue Target",               kn: "ರಕ್ಷಣಾ ಗುರಿ",                    hi: "बचाव लक्ष्य" },
  steerTo:            { en: "STEER TO",                    kn: "ಇತ್ತ ತಿರುಗಿಸಿ",                  hi: "इधर मुड़ें" },
  distance:           { en: "DISTANCE",                    kn: "ದೂರ",                           hi: "दूरी" },
  estArrival:         { en: "EST. ARRIVAL",                kn: "ಸರಾಸರಿ ಸಮಯ",                   hi: "औसत आगमन" },
  interceptActive:    { en: "RESCUE INTERCEPT ACTIVE",     kn: "ರಕ್ಷಣಾ ಕಾರ್ಯಾಚರಣೆ ಸಕ್ರಿಯ",       hi: "बचाव इंटरसेप्ट सक्रिय" },
  openGoogleMaps:     { en: "Open in Google Maps",          kn: "ಗೂಗಲ್ ಮ್ಯಾಪ್‌ನಲ್ಲಿ ತೆರೆಯಿರಿ",       hi: "गूगल मैप्स में खोलें" },
  downloadArea:       { en: "Download Current Area",       kn: "ಪ್ರದೇಶದ ನಕ್ಷೆ ಡೌನ್‌ಲೋಡ್",         hi: "वर्तमान क्षेत्र डाउनलोड करें" },
  settings:           { en: "Settings",                    kn: "ಸೆಟ್ಟಿಂಗ್ಸ್",                  hi: "सेटिंग्स" },

  // SOS page
  sosSuccessToast:    { en: "SOS Emergency Sent!",         kn: "SOS ತುರ್ತು ಕಳುಹಿಸಲಾಗಿದೆ!",    hi: "SOS आपातकाल भेजा गया!" },
  latitude:           { en: "Latitude",                    kn: "ಅಕ್ಷಾಂಶ",                      hi: "अक्षांश" },
  longitude:          { en: "Longitude",                   kn: "ರೇಖಾಂಶ",                       hi: "देशांतर" },
  shipRadioBridge:    { en: "Ship Radio Bridge",           kn: "ಹಡಗು ರೇಡಿಯೋ ಸೇತುವೆ",           hi: "जहाज रेडियो ब्रिज" },
  digitalBurst:       { en: "Digital Burst",               kn: "ಡಿಜಿಟಲ್ ಸಂಕೇತ",                hi: "डिजिटल बर्स्ट" },
  voiceMayday:        { en: "Voice Mayday",                kn: "ಧ್ವನಿ ಮೇಡೇ",                    hi: "वॉयस मेडे" },
  radioReceiver:      { en: "Radio Receiver",              kn: "ರೇಡಿಯೋ ರಿಸೀವರ್",               hi: "रेडियो रिसीवर" },
  broadcastSignal:    { en: "Broadcast Signal",            kn: "ಸಂಕೇತ ಪ್ರಸಾರ ಮಾಡಿ",           hi: "संकेत प्रसारित करें" },
  listenIncoming:     { en: "Listen for Incoming",         kn: "ಬರುವ ಸಂಕೇತ ಆಲಿಸಿ",              hi: "आने वाले संदेश सुनें" },

  // Login page
  email:              { en: "Email",                       kn: "ಇಮೇಲ್",                        hi: "ईमेल" },
  password:           { en: "Password",                    kn: "ಪಾಸ್‌ವರ್ಡ್",                   hi: "पासवर्ड" },
  loginEmailPlaceholder:    { en: "fisherman@email.com",   kn: "fisherman@email.com",           hi: "fisherman@email.com" },
  loginPasswordPlaceholder: { en: "Enter password",        kn: "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ",           hi: "पासवर्ड दर्ज करें" },
  pleaseWait:         { en: "Please Wait...",              kn: "ದಯವಿಟ್ಟು ಕಾಯಿರಿ...",           hi: "कृपया प्रतीक्षा करें..." },
  signup:             { en: "Create Account",              kn: "ಖಾತೆ ರಚಿಸಿ",                   hi: "खाता बनाएं" },
  login:              { en: "Login",                       kn: "ಲಾಗಿನ್",                        hi: "लॉग इन" },
  alreadyHaveAccount: { en: "Already have an account? Login", kn: "ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",  hi: "पहले से ही एक खाता है? लॉग इन करें" },
  dontHaveAccount:    { en: "Don't have an account? Sign Up", kn: "ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಾಯಿಸಿ",  hi: "एक खाता नहीं है? साइन अप करें" },
  or:                 { en: "or",                          kn: "ಅಥವಾ",                          hi: "या" },
  continueAsGuest:    { en: "Continue as Guest",           kn: "ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ",      hi: "अतिथि के रूप में जारी रखें" },
  fillAllFields:      { en: "Please fill all fields",      kn: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ತುಂಬಿಸಿ", hi: "कृपया सभी फ़ील्ड भरें" },
  passwordLengthError: { en: "Password must be at least 6 characters", kn: "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು ಇರಬೇಕು", hi: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए" },
  accountCreatedVerify: { en: "Account created! Please verify your email.", kn: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.", hi: "खाता बनाया गया! कृपया अपना ईमेल सत्यापित करें।" },
  loginSuccess:       { en: "Welcome back, Captain!",      kn: "ಸ್ವಾಗತ ಕ್ಯಾಪ್ಟನ್!",             hi: "स्वागत है, कप्तान!" },
  guestWelcome:       { en: "Welcome, Guest Navigator!",   kn: "ಸ್ವಾಗತ, ಅತಿಥಿ ನಾವಿಕ!",         hi: "स्वागत है, अतिथि नाविक!" },
  roleFisherman:      { en: "Fisherman",                   kn: "ಮೀನುಗಾರ",                      hi: "मछुआरा" },
  roleTourist:        { en: "Tourist",                     kn: "ಪ್ರವಾಸಿ",                       hi: "पर्यटक" },

  // Profile page
  userNameDemo:       { en: "Captain Rajan",               kn: "ಕ್ಯಾಪ್ಟನ್ ರಾಜನ್",             hi: "कैप्टन राजन" },
  verifiedFisherman:  { en: "Verified Vessel Master",      kn: "ಪರಿಶೀಲಿಸಿದ ನೌಕಾ ಮಾಸ್ಟರ್",      hi: "सत्यापित वेसल मास्टर" },
  safetyPro:          { en: "Safety Pro",                  kn: "ಸುರಕ್ಷತಾ ತಜ್ಞ",                 hi: "सुरक्षा प्रो" },
  experience:         { en: "Experience",                  kn: "ಅನಿಭವ",                        hi: "अनुभव" },
  level:              { en: "Level",                       kn: "ಹಂತ",                          hi: "स्तर" },
  seaReadiness:       { en: "Sea Readiness",               kn: "ಸಮುದ್ರ ಸನ್ನದ್ಧತೆ",              hi: "समुद्र तत्परता" },
  high:               { en: "High",                        kn: "ಹೆಚ್ಚು",                        hi: "उच्च" },
  identityMetrics:    { en: "IDENTITY METRICS",            kn: "ಗುರುತಿನ ಮಾಪನಗಳು",               hi: "पहचान मेट्रिक्स" },
  vesselMasterName:   { en: "Vessel Master Name",          kn: "ನೌಕಾ ಮಾಸ್ಟರ್ ಹೆಸರು",            hi: "जहाज मास्टर का नाम" },
  commLink:           { en: "Comm Link (Phone)",           kn: "ಸಂಪರ್ಕ ಲಿಂಕ್ (ಫೋನ್)",            hi: "कम्यूनिकेशन लिंक (फोन)" },
  vesselMaster:       { en: "Vessel Master",               kn: "ನೌಕಾ ಮಾಸ್ಟರ್",                  hi: "जहाज का मास्टर" },
  commDialect:        { en: "COMMUNICATION DIALECT",       kn: "ಸಂವಹನ ಉಪಭಾಷೆ",                hi: "संचार बोली" },
  adminLinks:         { en: "ADMINISTRATIVE LINKS",        kn: "ಆಡಳಿತಾತ್ಮಕ ಲಿಂಕ್‌ಗಳು",            hi: "प्रशासनिक लिंक" },
  safetyCertificates: { en: "Safety Certificates",         kn: "ಸುರಕ್ಷತಾ ಪ್ರಮಾಣಪತ್ರಗಳು",          hi: "सुरक्षा प्रमाणपत्र" },
  appSettings:        { en: "App Settings",                kn: "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್ಸ್",        hi: "सेटिंग्स" },
  logout:             { en: "Logout",                      kn: "ಲಾಗ್ ಔಟ್",                     hi: "लॉग आउट" },
  langChangedToast:   { en: "Language Updated",            kn: "ಭಾಷೆ ಬದಲಾಯಿಸಲಾಗಿದೆ",           hi: "भाषा अपडेट की गई" },
  chatbotTitle:       { en: "MITRA AI CORE",            kn: "ಮಿತ್ರ AI ಕೋರ್",                 hi: "मित्रा एआई कोर" },
  chatbotIntro:       { en: "I am **MITRA AI**, your Maritime Intelligence Assistant.", kn: "ನಾನು ಮಿತ್ರ AI, ನಿಮ್ಮ ಸಮುದ್ರ ಗುಪ್ತಚರ ಸಹಾಯಕ.", hi: "मैं **मित्रा एआई** हूँ, आपका समुद्री खुफिया सहायक।" },
  askMitra:           { en: "Ask Mitra AI...",             kn: "ಮಿತ್ರ AI ಅನ್ನು ಕೇಳಿ...",          hi: "मित्रा एआई से पूछें..." },
  bestFishingZones:   { en: "Best Fishing Zones",          kn: "ಉತ್ತಮ ಮೀನುಗಾರಿಕೆ ವಲಯಗಳು",        hi: "सर्वोत्तम मछली पकड़ने के क्षेत्र" },
  seaConditions:      { en: "Sea Conditions",              kn: "ಸಮುದ್ರದ ಪರಿಸ್ಥಿತಿಗಳು",            hi: "समुद्र की स्थिति" },
  safetyTips:         { en: "Safety Tips",                 kn: "ಸುರಕ್ಷತಾ ಸಲಹೆಗಳು",              hi: "सुरक्षा सुझाव" },
  navigationHelp:     { en: "Navigation Help",             kn: "ನೌಕಾಯಾನ ಸಹಾಯ",                 hi: "नेविगेशन सहायता" },
  emergencySteps:     { en: "Emergency Steps",             kn: "ತುರ್ತು ಕ್ರಮಗಳು",                  hi: "आपातकालीन कदम" },
  aiThinking:         { en: "Syncing data...",             kn: "ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",        hi: "डेटा सिंक हो रहा है..." },
  aiOnline:           { en: "Advanced Marine Intelligence • Online", kn: "ಸುಧಾರಿತ ಸಮುದ್ರ ಗುಪ್ತಚರ • ಆನ್‌ಲೈನ್", hi: "उन्नत समुद्री खुफिया • ऑनलाइन" },

  // Settings page
  languageSwitch:     { en: "Language",                    kn: "ಭಾಷೆ",                          hi: "भाषा" },
  displayLanguage:    { en: "Display Language",            kn: "ಪ್ರದರ್ಶನ ಭಾಷೆ",                hi: "प्रदर्शन भाषा" },
  notificationSettings: { en: "Push Notifications",       kn: "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",             hi: "पुश सूचनाएं" },

  // Alert engine
  dangerAlert:        { en: "🚨 DANGER ALERT",             kn: "🚨 ಅಪಾಯ ಎಚ್ಚರಿಕೆ",              hi: "🚨 खतरे की चेतावनी" },
  highWindAlert:      { en: "💨 HIGH WIND ALERT",          kn: "💨 ತೀವ್ರ ಗಾಳಿ ಎಚ್ಚರಿಕೆ",         hi: "💨 तेज हवा चेतावनी" },

  // Chatbot strings
  chatbotWelcome:     { en: "Welcome to Mitra AI. How can I assist you with your voyage today?", kn: "ಮಿತ್ರ AI ಗೆ ಸ್ವಾಗತ. ಇಂದು ನಿಮ್ಮ ಸಮುದ್ರಯಾನಕ್ಕೆ ನಾನು ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?", hi: "मित्रा एआई में आपका स्वागत है। मैं आपकी यात्रा में कैसे सहायता कर सकता हूँ?" },
  aiDefaultResponse:  { en: "Synchronizing with maritime data. Please rephrase your query.", kn: "ಸಮುದ್ರ ಮಾಹಿತಿಯನ್ನು ಸಿಂಕ್ ಮಾಡಲಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೊಮ್ಮೆ ಕೇಳಿ.", hi: "समुद्री डेटा के साथ सिंक हो रहा है। कृपया अपना प्रश्न दोबारा पूछें।" },

  // Notifications
  stayInformed:       { en: "Stay informed with real-time maritime intelligence.", kn: "ನೈಜ ಸಮಯದ ಸಮುದ್ರ ಮಾಹಿತಿಯೊಂದಿಗೆ ನವೀಕೃತವಾಗಿರಿ.", hi: "रीयल-टाइम समुद्री जानकारी के साथ अपडेट रहें।" },
  markAllAsRead:      { en: "Mark All Read",                kn: "ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ",    hi: "सभी को पढ़ा हुआ चिह्नित करें" },

  // Dashboard
  welcomeBack:        { en: "Welcome back,",               kn: "ಮರಳಿ ಸ್ವಾಗತ,",               hi: "वापस स्वागत है," },
  coastalIntelligence: { en: "Coastal Intelligence",        kn: "ಕರಾವಳಿ ಬುದ್ಧಿವಂತಿಕೆ",           hi: "तटीय बुद्धिमत्ता" },
  myVessel:           { en: "My Vessel",                   kn: "ನನ್ನ ನೌಕೆ",                   hi: "मेरा जहाज" },
  aiAssistant:        { en: "AI Assistant",                kn: "AI ಸಹಾಯಕ",                    hi: "AI सहायक" },
  emergencyAlerts:    { en: "Emergency Alerts",            kn: "ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು",              hi: "आपातकालीन अलर्ट" },
  liveTelemetry:      { en: "Live Telemetry",              kn: "ಲೈವ್ ಟೆಲಿಮೆಟ್ರಿ",                hi: "लाइव टेलीमेट्री" },
  temperature:        { en: "Temperature",                 kn: "ತಾಪಮಾನ",                        hi: "तापमान" },
  seaState:           { en: "Sea State",                   kn: "ಸಮುದ್ರದ ಸ್ಥಿತಿ",                  hi: "समुद्र की स्थिति" },
  calm:               { en: "Calm",                        kn: "ಶಾಂತ",                         hi: "शांत" },
  moderate:           { en: "Moderate",                    kn: "ಮಧ್ಯಮ",                        hi: "मध्यम" },
  humidity:           { en: "Humidity",                    kn: "ಆರ್ದ್ರತೆ",                      hi: "आर्द्रता" },
  rainfall:           { en: "Rainfall",                    kn: "ಮಳೆ",                           hi: "वर्षा" },
  weatherOutlook:     { en: "Weather Outlook",             kn: "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",              hi: "मौसम का पूर्वानुमान" },
  next8Hours:         { en: "Next 8 Hours",                kn: "ಮುಂದಿನ 8 ಗಂಟೆ",                 hi: "अगले 8 घंटे" },
  history:            { en: "History",                     kn: "ಇತಿಹಾಸ",                        hi: "इतिहास" },
  activeAlertCritical: { en: "Active Alert • Critical",    kn: "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆ • ಗಂಭೀರ",         hi: "सक्रिय अलर्ट • क्रिटिकल" },
  cautionMonitoring:  { en: "Caution • Monitoring",        kn: "ಎಚ್ಚರಿಕೆ • ಮೇಲ್ವಿಚಾರಣೆ",          hi: "सावधानी • निगरानी" },
  scanningTelemetry:  { en: "Scanning coastal telemetry...", kn: "ಕರಾವಳಿ ಮಾಹಿತಿಗಾಗಿ ಸ್ಕ್ಯಾನ್...", hi: "तटीय टेलीमेट्री स्कैनिंग..." },
  syncStatus:         { en: "Sync Status",                 kn: "ಸಿಂಕ್ ಸ್ಥಿತಿ",                   hi: "सिंक स्थिति" },
  locked:             { en: "LOCKED",                      kn: "ಲಾಕ್ ಆಗಿದೆ",                   hi: "लॉक" },
  monitoringStation:  { en: "Monitoring Station",          kn: "ಮೇಲ್ವಿಚಾರಣಾ ಕೇಂದ್ರ",            hi: "निगरानी स्टेशन" },
  missionVerdict:     { en: "Mission Verdict",             kn: "ಕಾರ್ಯಾಚರಣೆಯ ತೀರ್ಪು",             hi: "मिशन फैसला" },
  analyzingRisk:      { en: "Analyzing Ocean Risk...",      kn: "ಸಮುದ್ರದ ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ...",     hi: "महासागर जोखिम का विश्लेषण..." },
  oceanCurrents:      { en: "Ocean Currents",              kn: "ಸಮುದ್ರದ ಪ್ರವಾಹಗಳು",             hi: "समुद्री धाराएं" },
  windVector:         { en: "Wind Vector",                 kn: "ಗಾಳಿಯ ದಿಕ್ಕೆ",                   hi: "पवन वेक्टर" },
  nextTide:           { en: "Next Tide Update",            kn: "ಮುಂದಿನ ಉಬ್ಬರವಿಳಿತ",             hi: "अगला ज्वार अपडेट" },
  inMins:             { en: "IN {mins} MINS",              kn: "{mins} ನಿಮಿಷದಲ್ಲಿ",             hi: "{mins} मिनट में" },

  // Weather
  liveWeather:        { en: "Live Weather",                kn: "ನೇರ ಹವಾಮಾನ",                   hi: "लाइव मौसम" },
  safeToSail:         { en: "Safe to Sail",                kn: "ಹಡಗು ನಡೆಸಲು ಸುರಕ್ಷಿತ",           hi: "नौकायन के लिए सुरक्षित" },
  dangerToSail:       { en: "Danger to Sail",              kn: "ಹಡಗು ನಡೆಸಲು ಅಪಾಯಕಾರಿ",          hi: "नौकायन के लिए खतरनाक" },
  windSpeed:          { en: "Wind Speed",                  kn: "ಗಾಳಿಯ ವೇಗ",                  hi: "हवा की गति" },
  waveHeight:         { en: "Wave Height",                 kn: "ಅಲೆಗಳ ಎತ್ತರ",                  hi: "लहर की ऊंचाई" },
  locatingGps:        { en: "Locating via GPS...",         kn: "GPS ಮೂಲಕ ಹುಡುಕಲಾಗುತ್ತಿದೆ...",     hi: "GPS के माध्यम से खोज रहा है..." },

  // Fish Market
  buyFish:            { en: "Buy Catch",                   kn: "ಮೀನು ಖರೀದಿ",                  hi: "मछली खरीदें" },
  sellCatch:          { en: "Sell Catch",                  kn: "ಮೀನು ಮಾರಾಟ",                  hi: "मछली बेचें" },
  availableListings:  { en: "Available Listings",          kn: "ಲಭ್ಯವಿರುವ ಪಟ್ಟಿಗಳು",           hi: "उपलब्ध लिस्टिंग" },
  uploadPhoto:        { en: "Upload Catch Photo",          kn: "ಮೀನಿನ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",     hi: "मछली की फोटो अपलोड करें" },
  fishNameSpecies:    { en: "Fish Name / Species",         kn: "ಮೀನಿನ ಹೆಸರು / ತಳಿ",             hi: "मछली का नाम / प्रजाति" },
  fishNamePlaceholder: { en: "e.g. King Mackerel",          kn: "ಉದಾ: ಕಿಂಗ್ ಮ್ಯಾಕೆರೆಲ್",          hi: "उदा: किंग मैकेरल" },
  pricePerKg:         { en: "Price per KG (₹)",            kn: "ಕೆಜಿಗೆ ಬೆಲೆ (₹)",                 hi: "प्रति किलो कीमत (₹)" },
  availableQty:       { en: "Available Qty (KG)",          kn: "ಲಭ್ಯವಿರುವ ಪ್ರಮಾಣ (ಕೆಜಿ)",        hi: "उपलब्ध मात्रा (किग्रा)" },
  listItemMarket:     { en: "List Item on Market",         kn: "ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಿ",       hi: "मार्केट में लिस्ट करें" },
  callSeller:         { en: "Call Seller",                 kn: "ಮಾರಾಟಗಾರರಿಗೆ ಕರೆ ಮಾಡಿ",        hi: "विक्रेता को कॉल करें" },
  whatsappSeller:     { en: "WhatsApp",                    kn: "WhatsApp",                    hi: "WhatsApp" },
  listingSuccess:     { en: "Listing Added Successfully!", kn: "ಯಶಸ್ವಿಯಾಗಿ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಗಿದೆ!", hi: "लिस्टिंग सफलतापूर्वक जुड़ गई!" },
  browseBuy:          { en: "Browse & Buy",                kn: "ಬ್ರೌಸ್ ಮತ್ತು ಖರೀದಿಸಿ",            hi: "ब्राउज़ करें और खरीदें" },
  postListing:        { en: "Post a Listing",              kn: "ಪಟ್ಟಿಯನ್ನು ತಯಾರಿಸಿ",              hi: "एक लिस्टिंग पोस्ट करें" },
  searchMarket:       { en: "Search fish, seller, or location...", kn: "ಮೀನು, ಮಾರಾಟಗಾರ ಅಥವಾ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...", hi: "मछली, विक्रेता या स्थान खोजें..." },
  allTypes:           { en: "All Types",                   kn: "ಎಲ್ಲಾ ವಿಧಗಳು",                  hi: "सभी प्रकार" },
  prawn:              { en: "Prawn",                       kn: "ಸಿಗಡಿ",                        hi: "झींगा" },
  crab:               { en: "Crab",                        kn: "ಏಡಿ",                          hi: "केकड़ा" },
  squid:              { en: "Squid",                       kn: "ಸ್ಕ್ವಿಡ್",                      hi: "स्क्विड" },
  lobster:            { en: "Lobster",                     kn: "ನಳ್ಳಿ",                        hi: "लॉबस्टर" },
  other:              { en: "Other",                       kn: "ಇತರೆ",                         hi: "अन्य" },
  listingsFound:      { en: "listings found",              kn: "ಪಟ್ಟಿಗಳು ಕಂಡುಬಂದಿವೆ",            hi: "लिस्टिंग मिली" },
  activeListingsCount:{ en: "Active Listings",             kn: "ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು",                 hi: "सक्रिय लिस्टिंग" },
  avgPrice:           { en: "Avg Price",                   kn: "ಸರಾಸರಿ ಬೆಲೆ",                  hi: "औसत कीमत" },
  verified:           { en: "Verified",                    kn: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",                hi: "सत्यापित" },
  kgAvail:            { en: "kg available",                kn: "ಕೆಜಿ ಲಭ್ಯವಿದೆ",                  hi: "किलो उपलब्ध" },
  fresh:              { en: "Fresh",                       kn: "ತಾಜಾ",                         hi: "ताज़ा" },
  yourName:           { en: "Your Name *",                 kn: "ನಿಮ್ಮ ಹೆಸರು *",                  hi: "आपका नाम *" },
  phoneNumberTarget:  { en: "Phone Number * (Buyers will contact here)", kn: "ಫೋನ್ ಸಂಖ್ಯೆ * (ಖರೀದಿದಾರರು ಇಲ್ಲಿ ಸಂಪರ್ಕಿಸುತ್ತಾರೆ)", hi: "फोन नंबर *" },
  categoryTarget:     { en: "Category *",                  kn: "ವರ್ಗ *",                       hi: "श्रेणी *" },
  priceTarget:        { en: "Price (₹/kg) *",              kn: "ಬೆಲೆ (₹/ಕೆಜಿ) *",                hi: "कीमत (₹/किलो) *" },
  qtyTarget:          { en: "Quantity (kg) *",             kn: "ಪ್ರಮಾಣ (ಕೆಜಿ) *",                hi: "मात्रा (किलो) *" },
  descTarget:         { en: "Description (optional)",      kn: "ವಿವರಣೆ (ಐಚ್ಛಿಕ)",               hi: "विवरण (वैकल्पिक)" },
  gpsAutoDetect:      { en: "Your GPS location will be auto-detected when listing is posted", kn: "ಪಟ್ಟಿ ಮಾಡಿದಾಗ ನಿಮ್ಮ GPS ಸ್ಥಳವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತದೆ", hi: "आपका GPS स्थान स्वचालित रूप से पता लगाया जाएगा" },
  goLive:             { en: "Post Listing — Go Live",      kn: "ಪಟ್ಟಿಮಾಡಿ — ಲೈವ್ ಮಾಡಿ",           hi: "लिस्टिंग पोस्ट करें — लाइव जाएं" },
  removeListing:      { en: "Remove my listing",           kn: "ನನ್ನ ಪಟ್ಟಿಯನ್ನು ಅಳಿಸಿ",            hi: "लिस्टिंग हटाएं" },
  confirmDelete:      { en: "Confirm delete?",             kn: "ಅಳಿಸಲು ಖಚಿತಪಡಿಸಿ?",              hi: "हटाने की पुष्टि करें?" },
  yesRemove:          { en: "Yes, remove",                 kn: "ಹೌದು, ಅಳಿಸಿ",                  hi: "हाँ, निकालें" },
  cancel:             { en: "Cancel",                      kn: "ರದ್ದುಗೊಳಿಸಿ",                    hi: "रद्द करें" },
  loadingMarket:      { en: "Loading market data...",      kn: "ಮಾರುಕಟ್ಟೆ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",  hi: "लोड हो रहा है..." },
  noListings:         { en: "No listings found",           kn: "ಯಾವುದೇ ಪಟ್ಟಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",       hi: "कोई लिस्टिंग नहीं मिली" },
  beTheFirst:         { en: "Be the first to post a listing!", kn: "ಪಟ್ಟಿ ಮಾಡುವಲ್ಲಿ ಮೊದಲಿಗರಾಗಿರಿ!",   hi: "लिस्टिंग पोस्ट करने वाले पहले व्यक्ति बनें!" },
  tradeHub:           { en: "Live Trade Hub",              kn: "ಲೈವ್ ಟ್ರೇಡ್ ಹಬ್",                hi: "लाइव ट्रेड हब" },
  requestDelivery:    { en: "Request Delivery",            kn: "ಡೆಲಿವರಿ ವಿನಂತಿಸಿ",                 hi: "डिलीवरी का अनुरोध करें" },
  deliveryFee:        { en: "Delivery Fee",                kn: "ಡೆಲಿವರಿ ಶುಲ್ಕ",                    hi: "डिलीवरी शुल्क" },
  deliverySupport:    { en: "Mitra Logistics Support",     kn: "ಮಿತ್ರ ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಬೆಂಬಲ",            hi: "मित्रा लॉजिस्टिक्स सहायता" },
  deliveryDesc:       { en: "Get fresh fish delivered at ₹10/km.", kn: "ತಾಜಾ ಮೀನು ₹10/ಕಿಮೀ ದರದಲ್ಲಿ ಪಡೆಯಿರಿ.", hi: "₹10/किमी पर ताजी मछली प्राप्त करें।" },
  confirmDelivery:    { en: "Confirm Delivery",            kn: "ಡೆಲಿವರಿ ಖಚಿತಪಡಿಸಿ",               hi: "डिलीवरी की पुष्टि करें" },
  orderTotal:         { en: "Order Total",                 kn: "ಒಟ್ಟು ಮೊತ್ತ",                      hi: "कुल ऑर्डर" },
  distCharge:         { en: "Distance Charge",             kn: "ದೂರದ ಶುಲ್ಕ",                      hi: "दूरी शुल्क" },
  minOrder:           { en: "Min Order: 2kg",              kn: "ಕನಿಷ್ಠ ಆರ್ಡರ್: 2 ಕೆಜಿ",             hi: "न्यूनतम ऑर्डर: 2 किलो" },
  logisticMsg:        { en: "Your delivery request sent to Mitra Logistics!", kn: "ನಿಮ್ಮ ಡೆಲಿವರಿ ವಿನಂತಿಯನ್ನು ಮಿತ್ರ ಲಾಜಿಸ್ಟಿಕ್ಸ್ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ!", hi: "आपका डिलीवरी अनुरोध मित्रा लॉजिस्टिक्स को भेज दिया गया है!" },
  viewDeliveries:     { en: "My Deliveries",               kn: "ನನ್ನ ಡೆಲಿವರಿಗಳು",                  hi: "मेरी डिलीवरी" },

  // PFZ / Fish Detection
  pfzFinder:          { en: "PFZ Finder",                  kn: "ಮೀನುಗಾರಿಕೆ ವಲಯ ಪತ್ತೆ",           hi: "PFZ खोजक" },
  pfzDesc:            { en: "Satellite-based Potential Fishing Zones predicted via multi-parameter modeling.", kn: "ಉಪಗ್ರಹ ಆಧಾರಿತ ಮೀನುಗಾರಿಕೆ ವಲಯಗಳು.", hi: "उपग्रह आधारित मछली पकड़ने के क्षेत्र।" },
  satelliteSync:      { en: "SATELLITE SYNC",              kn: "ಸ್ಯಾಟಲೈಟ್ ಸಿಂಕ್",                hi: "सैटेलाइट सिंक" },
  liveSatellite:      { en: "LIVE SATELLITE",              kn: "ಲೈವ್ ಸ್ಯಾಟಲೈಟ್",                hi: "लाइव सैटेलाइट" },
  offlineEngine:      { en: "OFFLINE ENGINE",              kn: "ಆಫ್‌ಲೈನ್ ಇಂಜಿನ್",                hi: "ऑफ़लाइन इंजन" },
  syncing:            { en: "Syncing...",                  kn: "ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",            hi: "सिंक हो रहा है..." },
  forceSync:          { en: "FORCE SYNC",                  kn: "ಪೋರ್ಸ್ ಸಿಂಕ್",                  hi: "फोर्स सिंक" },
  lastSyncPrefix:     { en: "LAST UPDATED",                kn: "ಕೊನೆಯ ನವೀಕರಣ",                   hi: "अंतिम अपडेट" },
  yourVessel:         { en: "YOUR VESSEL",                 kn: "ನಿಮ್ಮ ನೌಕೆ",                    hi: "आपका जहाज" },
  pfzHotspot:         { en: "PFZ HOTSPOT",                 kn: "PFZ ಹಾಟ್‌ಸ್ಪಾಟ್",               hi: "PFZ हॉटस्पॉट" },
  confidence:         { en: "CONFIDENCE",                  kn: "ವಿಶ್ವಾಸಾರ್ಹತೆ",                  hi: "विश्वास" },
  score:              { en: "SCORE",                       kn: "ಅಂಕ",                          hi: "स्कोर" },
  vesselStatusOnline: { en: "VESSEL STATUS: ONLINE",       kn: "ನೌಕೆಯ ಸ್ಥಿತಿ: ಆನ್ಲೈನ್",          hi: "जहाज की स्थिति: ऑनलाइन" },
  vesselStatusOffline: { en: "VESSEL STATUS: OFFLINE",      kn: "ನೌಕೆಯ ಸ್ಥಿತಿ: ಆಫ್ಲೈನ್",          hi: "जहाज की स्थिति: ऑफ़लाइन" },
  hudHotspot:         { en: "HOTSPOT",                     kn: "ಹಾಟ್‌ಸ್ಪಾಟ್",                   hi: "हॉटस्पॉट" },
  hudModerate:        { en: "MODERATE",                    kn: "ಮಧ್ಯಮ",                        hi: "मध्यम" },
  hudFront:           { en: "CONVERGENCE FRONT",           kn: "ಅಲೆಗಳ ಸಂಗಮ",                    hi: "कन्वर्जेंस फ्रंट" },
  zoneAnalytics:      { en: "ZONE ANALYTICS",              kn: "ವಲಯ ವಿಶ್ಲೇಷಣೆ",                 hi: "क्षेत्र विश्लेषण" },
  targetLabel:        { en: "COORDINATES",                 kn: "ಸ್ಥಳದ ವಿವರ",                    hi: "निर्देशांक" },
  biologicalInsight:  { en: "BIOLOGICAL INSIGHT",           kn: "ಜೈವಿಕ ಒಳನೋಟ",                   hi: "जैविक विवरण" },
  sourceLabel:        { en: "SOURCE",                      kn: "ಮೂಲ",                          hi: "स्रोत" },
  safetyFactor:       { en: "SAFETY FACTOR",               kn: "ಸುರಕ್ಷತಾ ಅಂಶ",                   hi: "सुरक्षा कारक" },
  safeForDeployment:  { en: "SAFE FOR DEPLOYMENT",          kn: "ನಿಯೋಜನೆಗೆ ಸುರಕ್ಷಿತ",              hi: "जाने के लिए सुरक्षित" },
  cautionWaveDrift:   { en: "CAUTION: WAVE DRIFT",         kn: "ಎಚ್ಚರಿಕೆ: ಅಲೆಗಳ ಅಲೆತ",            hi: "सावधानी: लहर बहाव" },
  predictedSpecies:   { en: "PREDICTED SPECIES",           kn: "ನಿರೀಕ್ಷಿತ ಮೀನು ತಳಿಗಳು",          hi: "अनुमानित प्रजाति" },
  navigationTelemetry: { en: "NAVIGATION TELEMETRY",        kn: "ನೌಕಾಯಾನ ಮಾಹಿತಿ",                 hi: "नेविगेशन टेलीमेट्री" },
  habitatLabel:       { en: "HABITAT",                     kn: "ವಾಸಸ್ಥಾನ",                      hi: "आवास" },
  travelTime:         { en: "TRAVEL TIME",                 kn: "ಪ್ರಯಾಣದ ಸಮಯ",                   hi: "यात्रा का समय" },
  modelConfidence:    { en: "MODEL CONFIDENCE",            kn: "ಮಾದರಿ ವಿಶ್ವಾಸಾರ್ಹತೆ",              hi: "विश्वास" },
  selectZoneHint:     { en: "SELECT A ZONE ON THE MAP TO REVEAL DEEP ANALYTICS", kn: "ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಮ್ಯಾಪ್‌ನಲ್ಲಿ ವಲಯವನ್ನು ಆರಿಸಿ", hi: "विश्लेषण के लिए मानचित्र पर एक क्षेत्र चुनें" },
  activeHotspots:     { en: "ACTIVE REGIONAL HOTSPOTS",    kn: "ಸಕ್ರಿಯ ಪ್ರಾದೇಶಿಕ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",  hi: "सक्रिय क्षेत्र" },
  regionSync:         { en: "REAL-TIME REGION SYNC",       kn: "ಪ್ರಾದೇಶಿಕ ಸಿಂಕ್",                 hi: "रीयल-टाइम क्षेत्र सिंक" },
  probLabel:          { en: "FISH PROBABILITY",            kn: "ಮೀನಿನ ಸಾಧ್ಯತೆ",                  hi: "मछली की संभावना" },
  trainingLabel:      { en: "TRAINING AI...",              kn: "AI ತರಬೇತಿ...",                  hi: "प्रशिक्षण एआई..." },
  scienceTitle:       { en: "THE SCIENCE OF MITRA",        kn: "ಮಿತ್ರದ ವಿಜ್ಞಾನ",                   hi: "मित्रा का विज्ञान" },
  scienceDesc:        { en: "Our AI analyzes multiple satellite parameters to predict high-yield zones.", kn: "ಹೆಚ್ಚು ಮೀನು ಸಿಗುವ ವಲಯಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ನಮ್ಮ AI ಉಪಗ್ರಹ ಮಾಹಿತಿ ಬಳಸುತ್ತದೆ.", hi: "हमारा एआई उच्च मछली क्षेत्रों की भविष्यवाणी करने के लिए उपग्रह डेटा का विश्लेषण करता है।" },
  phytoplanktonMapping: { en: "PHYTOPLANKTON MAPPING",     kn: "ಫೈಟೊಪ್ಲಾಂಕ್ಟನ್ ಮ್ಯಾಪಿಂಗ್",       hi: "फाइटोप्लांकटन मैपिंग" },
  phytoDesc:          { en: "Chlorophyll fronts detected from space indicate food-rich waters.", kn: "ಆಕಾಶದಿಂದ ಪತ್ತೆಹಚ್ಚಲಾದ ಕ್ಲೋರೋಫಿಲ್ ಆಹಾರ ಸಮೃದ್ಧ ನೀರನ್ನು ಸೂಚಿಸುತ್ತದೆ.", hi: "क्लोरोफिल मोर्चे भोजन से भरपूर पानी का संकेत देते हैं।" },
  thermalFrontsMap:   { en: "THERMAL FRONTS MAP",          kn: "ಥರ್ಮಲ್ ಫ್ರಂಟ್ಸ್ ಮ್ಯಾಪ್",            hi: "थर्मल फ्रंट मैप" },
  thermalDesc:        { en: "Convergence of cold and warm currents create ideal habitat zones.", kn: "ತಂಪು ಮತ್ತು ಬೆಚ್ಚಗಿನ ಪ್ರವಾಹಗಳ ಸಂಗಮವು ಆದರ್ಶ ವಾಸಸ್ಥಾನಗಳನ್ನು ಸೃಷ್ಟಿಸುತ್ತದೆ.", hi: "ठंडी और गर्म धाराओं का संगम आदर्श आवास बनाता है।" },
  oceanColorImg:      { en: "OCEAN COLOR IMAGERY",         kn: "ಸಮುದ್ರದ ಬಣ್ಣದ ಚಿತ್ರಣ",            hi: "सागर रंग चित्रण" },
  colorDesc:          { en: "Subtle color variations reveal nutrient-dense pelagic hotspots.", kn: "ಸೂಕ್ಷ್ಮ ಬಣ್ಣದ ವ್ಯತ್ಯಾಸಗಳು ಪೋಷಕಾಂಶ-ದಟ್ಟವಾದ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ತೋರಿಸುತ್ತವೆ.", hi: "रंग भिन्नताएं पोषक तत्वों से भरपूर हॉटस्पॉट दिखाती हैं।" },
  bathymetricZone:    { en: "BATHYMETRIC ZONATION",        kn: "ಸಮುದ್ರದ ಆಳದ ವಲಯ",               hi: "बथिमेट्रिक क्षेत्र" },
  bathyDesc:          { en: "Shelf depth analysis predicts habitat-specific multi-species catch.", kn: "ಸಮುದ್ರದ ಆಳದ ವಿಶ್ಲೇಷಣೆಯು ವಿವಿಧ ಮೀನು ತಳಿಗಳನ್ನು ಊಹಿಸುತ್ತದೆ.", hi: "शेल्फ गहराई विश्लेषण विभिन्न प्रजातियों की भविष्यवाणी करता है।" },
  filterActive:       { en: "FILTER ACTIVE",               kn: "ಫಿಲ್ಟರ್ ಸಕ್ರಿಯ",                  hi: "फ़िल्टर सक्रिय" },
  mlEngine:           { en: "MACHINE LEARNING ENGINE",     kn: "ಮೆಷಿನ್ ಲರ್ನಿಂಗ್ ಇಂಜಿನ್",          hi: "मशीन लर्निंग इंजन" },
  mlTrainingViz:      { en: "ML TRAINING VISUALIZATION",   kn: "ML ತರಬೇತಿಯ ಚಿತ್ರಣ",             hi: "एमएल प्रशिक्षण चित्रण" },
  step1Title:         { en: "MULTI-SPECTRAL DATA",         kn: "ಮಲ್ಟಿ-ಸ್ಪೆಕ್ಟ್ರಲ್ ಮಾಹಿತಿ",           hi: "मल्टी-स्पेक्ट्रल डेटा" },
  step1Desc:          { en: "We analyze high-resolution SST and Chlorophyll spectral bands.", kn: "ನಾವು SST ಮತ್ತು ಕ್ಲೋರೋಫಿಲ್ ಸ್ಪೆಕ್ಟ್ರಲ್ ಬ್ಯಾಂಡ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತೇವೆ.", hi: "हम उच्च-रिज़ॉल्यूशन वाले एसएसटी और क्लोरोफिल का विश्लेषण करते हैं।" },
  step2Title:         { en: "CORRELATION MAPPING",         kn: "ಸಂಬಂಧಿತ ಮ್ಯಾಪಿಂಗ್",              hi: "सहसंबंध मानचित्रण" },
  step2Desc:          { en: "Neural networks correlate environmental data with catch logs.", kn: "ನರಮಂಡಲಗಳು ಪರಿಸರ ಮಾಹಿತಿಯನ್ನು ಕ್ಯಾಚ್ ಲಾಗ್‌ಗಳೊಂದಿಗೆ ಸಂಯೋಜಿಸುತ್ತವೆ.", hi: "न्यूरल नेटवर्क पर्यावरणीय डेटा को कैच लॉग के साथ जोड़ते हैं।" },
  step3Title:         { en: "LOCALIZED REFINEMENT",        kn: "ಸ್ಥಳೀಯ ಸುಧಾರಣೆ",                hi: "स्थानीय शोधन" },
  step3Desc:          { en: "Your feedback trains the model for specific regional precision.", kn: "ನಿಮ್ಮ ಫೀಡ್‌ಬ್ಯಾಕ್ ಪ್ರಾದೇಶಿಕ ನಿಖರತೆಗಾಗಿ ಮಾಡೆಲ್‌ಗೆ ತರಬೇತಿ ನೀಡುತ್ತದೆ.", hi: "आपकी प्रतिक्रिया मॉडल को विशिष्ट सटीकता के लिए प्रशिक्षित करती है।" },
  step3Prefix:        { en: "Optimizing for local",        kn: "ಸ್ಥಳೀಯಕ್ಕಾಗಿ ಉತ್ತಮಗೊಳಿಸಲಾಗುತ್ತಿದೆ",  hi: "स्थानीय के लिए अनुकूलन" },
  zonesRespecting:    { en: "ZONES RESPECTING CURRENT HABITAT LOGIC", kn: "ಪ್ರಸ್ತುತ ವಾಸಸ್ಥಾನದ ತರ್ಕದ ಅಡಿಯಲ್ಲಿನ ವಲಯಗಳು", hi: "वर्तमान आवास तर्क को दर्शाने वाले क्षेत्र" },
  multimodalWeighting: { en: "Multimodal Parameter Weighting", kn: "ಮಲ್ಟಿಮೋಡಲ್ ನಿಯತಾಂಕ ತೂಕ",           hi: "मल्टीमॉडल पैरामीटर वेटिंग" },
  modelAccuracyFactor: { en: "Model Accuracy Factor",          kn: "ಮಾಡೆಲ್ ನಿಖರತೆಯ ಅಂಶ",            hi: "मॉडल सटीकता कारक" },
  sstLabel:           { en: "SST",                         kn: "SST",                          hi: "SST" },
  sstBasis:           { en: "Thermal Basis",               kn: "ಥರ್ಮಲ್ ಆಧಾರ",                   hi: "थर्मल आधार" },
  planktonLabel:      { en: "Plankton",                    kn: "ಪ್ಲಾಂಕ್ಟನ್",                    hi: "प्लैंकटन" },
  planktonBasis:      { en: "Food Chain",                  kn: "ಆಹಾರ ಸರಪಳಿ",                    hi: "खाद्य श्रृंखला" },
  currentLabel:       { en: "Currents",                    kn: "ಪ್ರವಾಹ",                        hi: "धाराएं" },
  currentBasis:       { en: "Drift Logic",                 kn: "ಡ್ರಿಫ್ಟ್ ಲಾಜಿಕ್",                    hi: "बहाव तर्क" },
  colorLabel:         { en: "Water Color",                 kn: "ನೀರಿನ ಬಣ್ಣ",                      hi: "पानी का रंग" },
  colorBasis:         { en: "Turbidity Basis",             kn: "ಟರ್ಬಿಡಿಟಿ ಆಧಾರ",                  hi: "मैलापन आधार" },
  salinityLabel:      { en: "Salinity",                    kn: "ಲವಣಾಂಶ",                       hi: "लवणता" },
  salinityBasis:      { en: "Habitat Logic",               kn: "ವಾಸಸ್ಥಾನದ ತರ್ಕ",                  hi: "आवास तर्क" },
  thermoclineLabel:   { en: "Thermocline",                 kn: "ಥರ್ಮೋಕ್ಲೈನ್",                  hi: "थर्मोकलाइन" },
  thermoclineBasis:   { en: "Depth Anchor",                kn: "ಆಳದ ಮಾಹಿತಿ",                     hi: "गहराई एंकर" },
  turbidityLabel:     { en: "Turbidity",                   kn: "ಟರ್ಬಿಡಿಟಿ",                     hi: "मैलापन" },
  turbidityBasis:     { en: "Optical Basis",               kn: "ಆಪ್ಟಿಕಲ್ ಆಧಾರ",                  hi: "ऑप्टिकल आधार" },
  moonPhaseLabel:     { en: "Lunar Phase",                 kn: "ಚಂದ್ರನ ಹಂತ",                    hi: "चंद्र चरण" },
  moonPhaseBasis:     { en: "Gravity Logic",               kn: "ಗುರುತ್ವಾಕರ್ಷಣೆಯ ತರ್ಕ",             hi: "गुरुत्वाकर्षण तर्क" },
  justNow:            { en: "Just now",                    kn: "ಈಗ ತಾನೇ",                       hi: "अभी-अभी" },
  minsAgo:            { en: "{n}m ago",                    kn: "{n} ನಿಮಿಷದ ಹಿಂದೆ",              hi: "{n}m पहले" },
  hoursAgo:           { en: "{n}h ago",                    kn: "{n} ಗಂಟೆಯ ಹಿಂದೆ",               hi: "{n}h पहले" },
  step:               { en: "Step",                        kn: "ಹಂತ",                          hi: "कदम" },
  trainingLabelSuffix: { en: "TRAINING...",                kn: "ತರಬೇತಿ...",                    hi: "प्रशिक्षण एआई..." },
  aiPredictionActive: { en: "AI Prediction Active",        kn: "AI ಭವಿಷ್ಯವಾಣಿ ಸಕ್ರಿಯವಾಗಿದೆ",      hi: "एआई भविष्यवाणी सक्रिय" },
  catchProbability:   { en: "Catch Probability",           kn: "ಮೀನು ಸಿಗುವ ಸಾಧ್ಯತೆ",             hi: "पकड़ने की संभावना" },
  highDensity:        { en: "High Density Hotspot",        kn: "ಹೆಚ್ಚು ಮೀನು ಸಿಗುವ ವಲಯ",          hi: "उच्च घनत्व हॉटस्पॉट" },
  oceanFronts:        { en: "Convergence Zone",            kn: "ಸಮುದ್ರದ ಅಲೆಗಳ ಸಂಗಮ",            hi: "कन्वर्जेंस जोन" },
  sst:                { en: "Sea Temp (SST)",              kn: "ಸಮುದ್ರದ ತಾಪಮಾನ",                hi: "समुद्री तापमान" },
  chlorophyll:        { en: "Chlorophyll Front",           kn: "ಕ್ಲೋರೋಫಿಲ್ ಮುಂಭಾಗ",              hi: "क्लोरोफिल फ्रंट" },
  bathymetry:         { en: "Shelf Depth",                 kn: "ಸಮುದ್ರದ ಆಳ",                    hi: "शेल्फ़ गहराई" },
  currents:           { en: "Ocean Currents",              kn: "ಸಮುದ್ರದ ಪ್ರವಾಹಗಳು",             hi: "सुमुद्री धाराएं" },
  confirmCatch:       { en: "Confirm Catch",               kn: "ಮೀನು ಸಿಕ್ಕಿದ್ದನ್ನು ಖಚಿತಪಡಿಸಿ",   hi: "पुष्टि करें" },
  trainAI:            { en: "Teach AI",                    kn: "AI ಗೆ ತರಬೇತಿ ನೀಡಿ",              hi: "एआई को सिखाएं" },

  // --- Native Animations: Safety Module ---
  startDrill:         { en: "Start Drill",               kn: "ತರಬೇತಿ ಪ್ರಾರಂಭಿಸಿ",             hi: "ड्रिल शुरू करें" },
  previous:           { en: "Previous",                  kn: "ಹಿಂದಿನ",                        hi: "पिछला" },
  nextStep:           { en: "Next Step",                 kn: "ಮುಂದಿನ ಹಂತ",                   hi: "अगला कदम" },
  academyRank:        { en: "Academy Rank",              kn: "ಅಕಾಡೆಮಿ ಶ್ರೇಣಿ",               hi: "अकादमी रैंक" },
  masterMariner:      { en: "Master Mariner",            kn: "ಮಾಸ್ಟರ್ ಮ್ಯಾರಿನರ್",            hi: "मास्टर मेरिनर" },
  trainingHours:      { en: "Training Hours",            kn: "ತರಬೇತಿ ಅವಧಿ",                  hi: "प्रशिक्षण के घंटे" },
  mandatoryDrills:    { en: "Mandatory Drill Library",    kn: "ಕಡ್ಡಾಯ ತರಬೇತಿ ಸಂಗ್ರಹ",           hi: "अनिवार्य ड्रिल लाइब्रेरी" },
  communication:      { en: "Communication",             kn: "ಸಂಪರ್ಕ",                        hi: "संचार" },
  equipment:          { en: "Equipment",                 kn: "ಉಪಕರಣಗಳು",                     hi: "उपकरण" },
  drills:             { en: "Drills",                    kn: "ಅಭ್ಯಾಸ",                        hi: "अभ्यास" },
  vesselIntegrity:    { en: "Vessel Integrity",          kn: "ನೌಕೆಯ ಸುರಕ್ಷತೆ",                hi: "पोत अखंडता" },
  vhfTitle:           { en: "Marine VHF Radio Mastery",    kn: "VHF ರೇಡಿಯೋ ಬಳಕೆ",             hi: "वीएचएफ रेडियो महारत" },
  vhfStep1:           { en: "Tune to Emergency Channel 16",kn: "ತುರ್ತು ಚಾನೆಲ್ 16 ಗೆ ಟ್ಯೂನ್ ಮಾಡಿ",        hi: "आपातकालीन चैनल 16 पर ट्यून करें" },
  vhfStep2:           { en: "Broadcast: MAYDAY, MAYDAY, MAYDAY", kn: "ಮೇಡೇ, ಮೇಡೇ ಎಂದು 3 ಬಾರಿ ಹೇಳಿ", hi: "प्रसारण: मेडे, मेडे, मेडे" },
  vhfStep3:           { en: "Relay exact GPS coordinates & status", kn: "ನಿಮ್ಮ GPS ಸ್ಥಳವನ್ನು ಸ್ಪಷ್ಟಪಡಿಸಿ",  hi: "सटीक जीपीएस निर्देशांक रिले करें" },

  raftTitle:          { en: "Life Raft Deployment Drill",  kn: "ಲೈಫ್ ರಾಫ್ಟ್ ಬಳಕೆ",              hi: "लाइफ राफ्ट परिनियोजन ड्रिल" },
  raftStep1:          { en: "Release safety pin on the canister", kn: "ರಾಫ್ಟ್ ನ ಸೇಫ್ಟಿ ಪಿನ್ ತೆಗೆಯಿರಿ",     hi: "कनस्तर पर सेफ्टी पिन निकालें" },
  raftStep2:          { en: "Throw canister overboard firmly", kn: "ಕ್ಯಾನಿಸ್ಟರ್ ಅನ್ನು ನೀರಿಗೆ ಎಸೆಯಿರಿ",  hi: "कनस्तर को कसकर पानी में फेंकें" },
  raftStep3:          { en: "Yank painter line hard to inflate", kn: "ಗಾಳಿ ತುಂಬಲು ಹಗ್ಗವನ್ನು ಎಳೆಯಿರಿ",  hi: "हवा भरने के लिए डोरी को जोर से खींचे" },

  mobTitle:           { en: "Man Overboard (MOB) Rescue",  kn: "ಮನುಷ್ಯ ನೀರಿನಲ್ಲಿ ಬಿದ್ದಾಗ",         hi: "मैन ओवरबोर्ड बचाव" },
  mobStep1:           { en: "Shout 'Man Overboard!' & point constantly", kn: "'ಮನುಷ್ಯ ನೀರಿನಲ್ಲಿ' ಎಂದು ಕಿರುಚಿರಿ", hi: "मैन ओवरबोर्ड चिल्लायें और इशारा करें" },
  mobStep2:           { en: "Immediately toss life ring to victim", kn: "ಲೈಫ್ ರಿಂಗ್ ಅನ್ನು ಎಸೆಯಿರಿ",      hi: "तुरंत पीड़ित को लाइफ रिंग फेंकें" },
  mobStep3:           { en: "Execute Williamson Turn to retrieve", kn: "ಹಡಗನ್ನು ತಿರುಗಿಸಿ ರಕ್ಷಿಸಿ",        hi: "बचाने के लिए विलियमसन टर्न करें" },

  flareTitle:         { en: "Distress Flare Operations",   kn: "ತುರ್ತು ಫ್ಲೇರ್ ಬಳಕೆ",             hi: "डिस्ट्रेस फ्लेयर संचालन" },
  flareStep1:         { en: "Twist and remove bottom strike cap", kn: "ಬಾಟಮ್ ಕ್ಯಾಪ್ ತೆಗೆಯಿರಿ",            hi: "निचले कैप को घुमाएं और हटाएं" },
  flareStep2:         { en: "Hold tightly & angle away downwind", kn: "ಗಾಳಿಯ ದಿಕ್ಕಿನಿಂದ ದೂರ ಹಿಡಿಯಿರಿ",    hi: "कसकर पकड़ें और नीचे की ओर कोण बनाएं" },
  flareStep3:         { en: "Pull striker string sharply to ignite", kn: "ಬೆಂಕಿ ಹಚ್ಚಲು ದಾರವನ್ನು ಎಳೆಯಿರಿ",     hi: "प्रज्वलित करने के लिए डोरी खींचे" },

  // System and Map
  systemActive:       { en: "SYSTEM ACTIVE",               kn: "ವ್ಯವಸ್ಥೆ ಸಕ್ರಿಯವಾಗಿದೆ",           hi: "सिस्टम सक्रिय" },
  
  // Chatbot responses
  chatEmergency:      { en: "🚨 EMERGENCY PROTOCOL: 1. Press SOS button immediately. 2. Call India Coast Guard: 1554. Help is on its way!", kn: "🚨 ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ: ತಕ್ಷಣ SOS ಸಿಗ್ನಲ್ ಕಳುಹಿಸಿ. ಭಾರತೀಯ ಕೋಸ್ಟ್ ಗಾರ್ಡ್ ಅನ್ನು 1554 ಗೆ ಕರೆಯಿರಿ. ಸಹಾಯ ಬದಿಯಲ್ಲಿದೆ!", hi: "🚨 आपातकालीन प्रोटोकॉल: 1. तुरंत SOS बटन दबाएं। 2. भारतीय तटरक्षक बल को 1554 पर कॉल करें। मदद आ रही है!" },
  chatSafety:         { en: "⛑️ SAFETY ESSENTIALS: Always wear life jackets, carry a VHF radio, and check weather before departing.", kn: "⛑️ ಸುರಕ್ಷತಾ ಕ್ರಮಗಳು: ಯಾವಾಗಲೂ ಲೈಫ್ ಜಾಕೆಟ್ ಧರಿಸಿ, VHF ರೇಡಿಯೋ ಇಟ್ಟುಕೊಳ್ಳಿ ಮತ್ತು ಹವಾಮಾನ ಪರಿಶೀಲಿಸಿ.", hi: "⛑️ सुरक्षा अनिवार्य: हमेशा लाइफ जैकेट पहनें, वीएचएफ रेडियो साथ रखें और निकलने से पहले मौसम की जांच करें।" },
  chatNavigate:       { en: "🧭 NAVIGATION: Use GPS and cross-reference with charts. Avoid shipping lanes without AIS.", kn: "🧭 ನೌಕಾಯಾನ: GPS ಬಳಸಿ ಮತ್ತು ಚಾರ್ಟ್‌ಗಳೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ. AIS ಇಲ್ಲದೆ ಹಡಗು ಹಾದಿಗಳನ್ನು ತಪ್ಪಿಸಿ.", hi: "🧭 नेविगेशन: जीपीएस का उपयोग करें और मानचित्रों के साथ क्रॉस-रेफरेंस करें। AIS के बिना शिपिंग लेन से बचें।" },
  chatDefault:        { en: "I specialize in maritime safety and fishing. Try asking about weather or fishing zones!", kn: "ನಾನು ಸಮುದ್ರ ಸುರಕ್ಷೆ ಮತ್ತು ಮೀನುಗಾರಿಕೆ ಬಗ್ಗೆ ಮಾಹಿತಿ ನೀಡಬಲ್ಲೆ. ಹವಾಮಾನ ಅಥವಾ ಮೀನುಗಾರಿಕೆ ಬಗ್ಗೆ ಕೇಳಿ!", hi: "मैं समुद्री सुरक्षा और मछली पकड़ने में विशेषज्ञ हूं। मौसम या मछली पकड़ने के क्षेत्रों के बारे में पूछने का प्रयास करें!" },
  chatHello:          { en: "Greetings! I am MITRA, your Marine Assistant. How can I help you today?", kn: "ನಮಸ್ಕಾರ! ನಾನು ಮಿತ್ರ, ನಿಮ್ಮ ಸಮುದ್ರ ಸಹಾಯಕ. ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?", hi: "नमस्ते! मैं मित्रा हूं, आपका समुद्री सहायक। आज मैं आपकी क्या मदद कर सकता हूँ?" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[language] ?? entry["en"] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
